### ISSUE TITLE
Shortcuts don't work

### ISSUE THREAD

**Issue by Djaler** [elementary/gala#193]
Juno. Sometimes keyboard shortcuts (like Win+T or volume control) stops working. If I went to settings and reassign shortcut, it starts working again.

**Comment by Djaler** [comment]
Also, reset through the gsettings (for example `gsettings reset org.gnome.settings-daemon.plugins.media-keys volume-down`) helps with this

**Comment by Djaler** [comment]
And restarting gala help too

**Comment by Djaler** [comment]
Also, killing gsd-media-keys helps too (it restarts automatically)

**Comment by peteruithoven** [comment]
`gsd-media-keys`? Are you sure that's included in elementary OS by default? I experience the same issue but don't seem to have that tool.
```
$ gsd-media-keys
gsd-media-keys: command not found
```

**Comment by Djaler** [comment]
Looks like binary is `/usr/lib/gnome-settings-daemon/gsd-media-keys`, check this place

**Comment by Djaler** [comment]
I just caught this bug. And what I see in `journalctl` after killing gsd-media-keys:
```мар 19 09:18:27 juno gnome-session[1285]: gnome-session-binary[1285]: WARNING: Application 'org.gnome.SettingsDaemon.MediaKeys-pantheon.desktop' killed by signal 15
мар 19 09:18:27 juno gnome-session-binary[1285]: WARNING: Application 'org.gnome.SettingsDaemon.MediaKeys-pantheon.desktop' killed by signal 15
мар 19 09:18:27 juno dbus-daemon[869]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.77' (uid=1000 pid=4535 comm="/usr/lib/gnome-settings-daemon/gsd-media-keys " label="unconfined")```

**Comment by Djaler** [comment]
Hmm, maybe this is the reason https://github.com/elementary/session-settings/commit/2d64ecbf93d77ee681867d16a592adb1829df629

**Comment by peteruithoven** [comment]
I overlooked you're running Juno. I'm on Loki. But I experience the same issue sometimes. Restarting Gala helps for me too. 

I seem to have that binary, but it doesn't seem to be running in the background. If I filter `htop` or `ps` on "media" I find 0 processes. 

I think I'll stop commenting and keep this issue focused on Juno.

**Comment by Djaler** [comment]
@codygarver can you look at this?

**Comment by Djaler** [comment]
After many days with old version of this file https://github.com/elementary/session-settings/commit/2d64ecbf93d77ee681867d16a592adb1829df629 I can confirm that bug is gone. So, can we revert it?

**Comment by Djaler** [comment]
Fixed with https://github.com/elementary/session-settings/commit/c1310e9bc1b855df578e90696ad437c3f49b4934, thank you

**Comment by Djaler** [comment]
Hmm, I reopen this again, cause I experienced this again, after logout.

**Comment by Djaler** [comment]
I can reproduce this bug by `sudo service lightdm restart`

**Comment by Djaler** [comment]
I can provide more info about this.
This is a piece of log just after boot, when I experienced by the issue:
`
journalctl -b 0 | grep gnome                           
апр 04 21:34:55 juno systemd[1]: session-c1.scope: Killing process 1000 (gnome-keyring-d) with signal SIGTERM.
апр 04 21:34:55 juno dbus-daemon[1292]: [session uid=1000 pid=1292] Activating via systemd: service name='org.a11y.Bus' unit='at-spi-dbus-bus.service' requested by ':1.5' (uid=1000 pid=1367 comm="/usr/lib/gnome-session/gnome-session-check-acceler" label="unconfined")
апр 04 21:34:55 juno at-spi-bus-launcher[1369]: dbus-daemon[1374]: Activating service name='org.a11y.atspi.Registry' requested by ':1.0' (uid=1000 pid=1367 comm="/usr/lib/gnome-session/gnome-session-check-acceler" label="unconfined")
апр 04 21:34:55 juno gnome-session[1260]: gnome-session-binary[1260]: WARNING: Error while executing session-migration: Не удалось выполнить процесс-потомок «session-migration» (No such file or directory)
апр 04 21:34:55 juno gnome-session-binary[1260]: WARNING: Error while executing session-migration: Не удалось выполнить процесс-потомок «session-migration» (No such file or directory)
апр 04 21:34:55 juno gnome-session[1260]: gnome-session-binary[1260]: WARNING: Could not parse desktop file gnome-user-share-pantheon.desktop or it references a not found TryExec binary
апр 04 21:34:55 juno gnome-session-binary[1260]: WARNING: Could not parse desktop file gnome-user-share-pantheon.desktop or it references a not found TryExec binary
апр 04 21:34:55 juno gnome-session[1260]: gnome-session-binary[1260]: WARNING: Could not parse desktop file onboard-autostart-pantheon.desktop or it references a not found TryExec binary
апр 04 21:34:55 juno gnome-session-binary[1260]: WARNING: Could not parse desktop file onboard-autostart-pantheon.desktop or it references a not found TryExec binary
апр 04 21:34:56 juno gnome-session[1260]: gnome-session-binary[1260]: WARNING: App 'elementary-dpms-helper.desktop' exited with code 1
апр 04 21:34:56 juno gnome-session[1260]: gnome-session-binary[1260]: WARNING: App 'spice-vdagent.desktop' exited with code 1
апр 04 21:34:56 juno gnome-session-binary[1260]: WARNING: App 'elementary-dpms-helper.desktop' exited with code 1
апр 04 21:34:56 juno gnome-session-binary[1260]: WARNING: App 'spice-vdagent.desktop' exited with code 1
апр 04 21:34:56 juno gnome-keyring-ssh-pantheon.desktop[1413]: SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
апр 04 21:34:56 juno gnome-keyring-gpg-pantheon.desktop[1424]: SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
апр 04 21:34:56 juno dbus-daemon[1292]: [session uid=1000 pid=1292] Activating via systemd: service name='org.gtk.vfs.Daemon' unit='gvfs-daemon.service' requested by ':1.27' (uid=1000 pid=1401 comm="/usr/lib/gnome-settings-daemon/gsd-xsettings " label="unconfined")
апр 04 21:34:56 juno gnome-keyring-pkcs11-pantheon.desktop[1451]: SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
апр 04 21:34:56 juno dbus-daemon[866]: [system] Activating via systemd: service name='org.freedesktop.locale1' unit='dbus-org.freedesktop.locale1.service' requested by ':1.37' (uid=1000 pid=1403 comm="/usr/lib/gnome-settings-daemon/gsd-keyboard " label="unconfined")
апр 04 21:34:56 juno dbus-daemon[866]: [system] Activating via systemd: service name='org.freedesktop.ColorManager' unit='colord.service' requested by ':1.39' (uid=1000 pid=1421 comm="/usr/lib/gnome-settings-daemon/gsd-color " label="unconfined")
апр 04 21:34:56 juno gsd-xsettings[1401]: Failed to get current display configuration state: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.Mutter.DisplayConfig" does not exist
апр 04 21:34:56 juno dbus-daemon[866]: [system] Activating via systemd: service name='org.freedesktop.timedate1' unit='dbus-org.freedesktop.timedate1.service' requested by ':1.42' (uid=1000 pid=1405 comm="/usr/lib/gnome-settings-daemon/gsd-datetime " label="unconfined")
апр 04 21:34:56 juno gsd-sharing[1412]: Failed to StopUnit service: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit gnome-remote-desktop.service not loaded.
апр 04 21:34:56 juno gnome-session-binary[1260]: Entering running state
апр 04 21:34:57 juno dbus-daemon[1292]: [session uid=1000 pid=1292] Activating service name='org.gnome.OnlineAccounts' requested by ':1.57' (uid=1000 pid=1664 comm="/usr/lib/gvfs/gvfs-goa-volume-monitor " label="unconfined")
апр 04 21:34:57 juno dbus-daemon[1292]: [session uid=1000 pid=1292] Activating service name='org.gnome.Identity' requested by ':1.59' (uid=1000 pid=1668 comm="/usr/lib/gnome-online-accounts/goa-daemon " label="unconfined")
апр 04 21:34:57 juno dbus-daemon[1292]: [session uid=1000 pid=1292] Successfully activated service 'org.gnome.Identity'
апр 04 21:34:57 juno dbus-daemon[1292]: [session uid=1000 pid=1292] Successfully activated service 'org.gnome.OnlineAccounts'
апр 04 21:34:57 juno dbus-daemon[1292]: [session uid=1000 pid=1292] Activating via systemd: service name='org.gnome.evolution.dataserver.Sources5' unit='evolution-source-registry.service' requested by ':1.47' (uid=1000 pid=1576 comm="wingpanel " label="unconfined")
апр 04 21:34:59 juno gnome-keyring-daemon[1257]: asked to register item /org/freedesktop/secrets/collection/login/1, but it's already registered
апр 04 21:35:00 juno gnome-keyring-daemon[1257]: asked to register item /org/freedesktop/secrets/collection/login/1, but it's already registered
`

And this is after normal boot, when there are no issue:
`
journalctl -b 0 | grep gnome
апр 04 22:09:15 juno systemd[1]: session-c1.scope: Killing process 1005 (gnome-keyring-d) with signal SIGTERM.
апр 04 22:09:16 juno dbus-daemon[1252]: [session uid=1000 pid=1252] Activating via systemd: service name='org.a11y.Bus' unit='at-spi-dbus-bus.service' requested by ':1.5' (uid=1000 pid=1326 comm="/usr/lib/gnome-session/gnome-session-check-acceler" label="unconfined")
апр 04 22:09:16 juno at-spi-bus-launcher[1328]: dbus-daemon[1333]: Activating service name='org.a11y.atspi.Registry' requested by ':1.0' (uid=1000 pid=1326 comm="/usr/lib/gnome-session/gnome-session-check-acceler" label="unconfined")
апр 04 22:09:16 juno gnome-session[1219]: gnome-session-binary[1219]: WARNING: Error while executing session-migration: Не удалось выполнить процесс-потомок «session-migration» (No such file or directory)
апр 04 22:09:16 juno gnome-session-binary[1219]: WARNING: Error while executing session-migration: Не удалось выполнить процесс-потомок «session-migration» (No such file or directory)
апр 04 22:09:16 juno gnome-session[1219]: gnome-session-binary[1219]: WARNING: Could not parse desktop file gnome-user-share-pantheon.desktop or it references a not found TryExec binary
апр 04 22:09:16 juno gnome-session-binary[1219]: WARNING: Could not parse desktop file gnome-user-share-pantheon.desktop or it references a not found TryExec binary
апр 04 22:09:16 juno gnome-session[1219]: gnome-session-binary[1219]: WARNING: Could not parse desktop file onboard-autostart-pantheon.desktop or it references a not found TryExec binary
апр 04 22:09:16 juno gnome-session-binary[1219]: WARNING: Could not parse desktop file onboard-autostart-pantheon.desktop or it references a not found TryExec binary
апр 04 22:09:16 juno gnome-session[1219]: gnome-session-binary[1219]: WARNING: App 'elementary-dpms-helper.desktop' exited with code 1
апр 04 22:09:16 juno gnome-session[1219]: gnome-session-binary[1219]: WARNING: App 'spice-vdagent.desktop' exited with code 1
апр 04 22:09:16 juno gnome-session-binary[1219]: WARNING: App 'elementary-dpms-helper.desktop' exited with code 1
апр 04 22:09:16 juno gnome-session-binary[1219]: WARNING: App 'spice-vdagent.desktop' exited with code 1
апр 04 22:09:16 juno gnome-keyring-pkcs11-pantheon.desktop[1405]: SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
апр 04 22:09:16 juno gnome-keyring-ssh-pantheon.desktop[1376]: SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
апр 04 22:09:16 juno dbus-daemon[1252]: [session uid=1000 pid=1252] Activating via systemd: service name='org.gtk.vfs.Daemon' unit='gvfs-daemon.service' requested by ':1.29' (uid=1000 pid=1395 comm="/usr/lib/gnome-settings-daemon/gsd-housekeeping " label="unconfined")
апр 04 22:09:16 juno dbus-daemon[888]: [system] Activating via systemd: service name='org.freedesktop.locale1' unit='dbus-org.freedesktop.locale1.service' requested by ':1.39' (uid=1000 pid=1363 comm="/usr/lib/gnome-settings-daemon/gsd-keyboard " label="unconfined")
апр 04 22:09:16 juno dbus-daemon[888]: [system] Activating via systemd: service name='org.freedesktop.timedate1' unit='dbus-org.freedesktop.timedate1.service' requested by ':1.35' (uid=1000 pid=1365 comm="/usr/lib/gnome-settings-daemon/gsd-datetime " label="unconfined")
апр 04 22:09:16 juno gsd-xsettings[1358]: Failed to get current display configuration state: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.Mutter.DisplayConfig" does not exist
апр 04 22:09:16 juno dbus-daemon[888]: [system] Activating via systemd: service name='org.freedesktop.ColorManager' unit='colord.service' requested by ':1.42' (uid=1000 pid=1384 comm="/usr/lib/gnome-settings-daemon/gsd-color " label="unconfined")
апр 04 22:09:16 juno gsd-sharing[1372]: Failed to StopUnit service: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit gnome-remote-desktop.service not loaded.
апр 04 22:09:16 juno gnome-session-binary[1219]: Entering running state
апр 04 22:09:17 juno dbus-daemon[1252]: [session uid=1000 pid=1252] Activating service name='org.gnome.OnlineAccounts' requested by ':1.57' (uid=1000 pid=1623 comm="/usr/lib/gvfs/gvfs-goa-volume-monitor " label="unconfined")
апр 04 22:09:17 juno dbus-daemon[1252]: [session uid=1000 pid=1252] Activating service name='org.gnome.Identity' requested by ':1.59' (uid=1000 pid=1627 comm="/usr/lib/gnome-online-accounts/goa-daemon " label="unconfined")
апр 04 22:09:17 juno dbus-daemon[1252]: [session uid=1000 pid=1252] Successfully activated service 'org.gnome.OnlineAccounts'
апр 04 22:09:17 juno dbus-daemon[1252]: [session uid=1000 pid=1252] Successfully activated service 'org.gnome.Identity'
апр 04 22:09:17 juno dbus-daemon[1252]: [session uid=1000 pid=1252] Activating via systemd: service name='org.gnome.evolution.dataserver.Sources5' unit='evolution-source-registry.service' requested by ':1.47' (uid=1000 pid=1534 comm="wingpanel " label="unconfined")
апр 04 22:09:20 juno org.freedesktop.thumbnails.Thumbnailer1[1252]: Registered thumbailer gnome-thumbnail-font --size %s %u %o
апр 04 22:09:34 juno org.gnome.SettingsDaemon.MediaKeys-pantheon.desktop[1404]: [DEBUG 22:09:33.671317] Settings.vala:163: Loading settings from schema 'io.elementary.terminal.saved-state'
апр 04 22:09:34 juno org.gnome.SettingsDaemon.MediaKeys-pantheon.desktop[1404]: [DEBUG 22:09:33.672277] Settings.vala:163: Loading settings from schema 'io.elementary.terminal.settings'
апр 04 22:09:34 juno org.gnome.SettingsDaemon.MediaKeys-pantheon.desktop[1404]: [WARNING 22:09:33.775970] [Vte] (../../src/vtegtk.cc:1915):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)
апр 04 22:09:34 juno org.gnome.SettingsDaemon.MediaKeys-pantheon.desktop[1404]: [WARNING 22:09:33.775999] [Vte] (../../src/vtegtk.cc:1915):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)
апр 04 22:09:34 juno org.gnome.SettingsDaemon.MediaKeys-pantheon.desktop[1404]: [WARNING 22:09:33.776019] [Vte] (../../src/vtegtk.cc:1915):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)
апр 04 22:09:34 juno org.gnome.SettingsDaemon.MediaKeys-pantheon.desktop[1404]: [WARNING 22:09:33.776036] [Vte] (../../src/vtegtk.cc:1915):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)
апр 04 22:09:34 juno org.gnome.SettingsDaemon.MediaKeys-pantheon.desktop[1404]: [WARNING 22:09:33.776058] [Vte] (../../src/vtegtk.cc:1915):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)
апр 04 22:10:17 juno org.gnome.SettingsDaemon.MediaKeys-pantheon.desktop[1404]: [DEBUG 22:09:37.850775] Settings.vala:163: Loading settings from schema 'io.elementary.terminal.saved-state'
апр 04 22:10:17 juno org.gnome.SettingsDaemon.MediaKeys-pantheon.desktop[1404]: [DEBUG 22:09:37.851123] Settings.vala:163: Loading settings from schema 'io.elementary.terminal.settings'
апр 04 22:10:17 juno org.gnome.SettingsDaemon.MediaKeys-pantheon.desktop[1404]: [WARNING 22:09:37.939051] [Vte] (../../src/vtegtk.cc:1915):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)
апр 04 22:10:17 juno org.gnome.SettingsDaemon.MediaKeys-pantheon.desktop[1404]: [WARNING 22:09:37.939094] [Vte] (../../src/vtegtk.cc:1915):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)
апр 04 22:10:17 juno org.gnome.SettingsDaemon.MediaKeys-pantheon.desktop[1404]: [WARNING 22:09:37.939129] [Vte] (../../src/vtegtk.cc:1915):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)
апр 04 22:10:17 juno org.gnome.SettingsDaemon.MediaKeys-pantheon.desktop[1404]: [WARNING 22:09:37.939169] [Vte] (../../src/vtegtk.cc:1915):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)
апр 04 22:10:17 juno org.gnome.SettingsDaemon.MediaKeys-pantheon.desktop[1404]: [WARNING 22:09:37.939201] [Vte] (../../src/vtegtk.cc:1915):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)
`

**Comment by Djaler** [comment]
It looks like gsd-media-keys is loaded, but hunged up, so it does not respond to anything

**Comment by Djaler** [comment]
Maybe we can somehow ping it, or do something to test it after loading

**Comment by Djaler** [comment]
Just a reminder. Still doesn't work in fresh ISO

**Comment by cassidyjames** [comment]
@Djaler is this happening lately? I don't know that I've ever seen it.

**Comment by danrabbit** [comment]
Dropping from the milestone since we can't reproduce

**Comment by Djaler** [comment]
@cassidyjames happen just now

**Comment by peteruithoven** [comment]
It has also happened to me a few times on an up to date Juno.

**Comment by peteruithoven** [comment]
Just to clarify, when you experience this issue a workaround is restarting gsd-media-keys by running:
```
killall gsd-media-keys
```

**Comment by InsanusMokrassar** [comment]
Hello. I have faced this problem too and created [this](https://gist.github.com/InsanusMokrassar/7db797a3e34badc28840df76542e445b) script for fixing it until it will be fixed in system

**Comment by Gabriel-p** [comment]
> killall gsd-media-keys

I'm also experiencing this issue and the above command solves it.

**Comment by sollymay** [comment]
Same issue here. Seems like the script fixes only Volume controls for me, but not playback controls. there is no way to fix playback controls. My media shortcuts started failing around May as well and I've been able to recover them from time to time using dconf editor and updating values (setting back to default and then back to custom values AudioNext, AudioPrev, etc, but this time seems different. T

This time no matter what I do it is still broken for playback controls.

**Comment by aspersieman** [comment]
Hell all. I have the same issue as reported by @sollymay. If I run the script from @InsanusMokrassar or kill the gsd-media-keys process sometimes my volume-down media key starts working, but none of the other ones do.

HTH

**Comment by aspersieman** [comment]
Another note is that I cannot even remap the keys in System Settings > Keyboard > Shortcuts > Media to the media keys on the keyboard. I can, however, remap them to SUPER+MEDIA KEY

**Comment by jdaeira** [comment]
I am also experiencing issues with the media keys. They work for a while and then all of a sudden stop working. The killall gsd-media-keys for me only brings back the volume keys. The previous/play/next keys don't work.

**Comment by jdaeira** [comment]
Removing the Google Play Music extension from Google Chrome seems to have fixed the issue.

**Comment by vikasnataraja** [comment]
The `killall gsd-media-keys` worked for me. But this issue keeps repeating and there don't seem to be any common patterns or actions to reproduce (for me) and just seems to happen at random. Will comment again if I notice a specific series of actions causing this issue.

**Comment by panoskouf** [comment]
I started experiencing this issue since I added some custom shortcuts that invoke python scripts. Sometimes after start up, none of the custom shortcuts(python scripts or not) or the media keys shortcuts work and I have to restart.

Not sure if this is relevant either, I also have a python script set to run on start up which sometimes also fails to start. There seems to be some kind of race conditions.

**Comment by vkaam** [comment]
Was experiencing the same issue after my laptop being suspended, fixed it by disabling Hardware Media Key Handling in Google Chrome.

**Comment by CCaroV** [comment]
Had this same issue today. `killall gsd-media-keys` helped for noe. I'm going to try @vkaam idea below.

**Comment by louay2580** [comment]
This seems like my issue, i have a usb keyboard with phisical"vol+, vol-, next, prev, pause/play" buttons and only vol +, vol- are working although with the help of an cli app called evtest
it shows that it reads that there are button pressed
`Testing ... (interrupt to exit)
Event: time 1584643472.022651, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00e9
Event: time 1584643472.022651, type 1 (EV_KEY), code 115 (KEY_VOLUMEUP), value 1
Event: time 1584643472.022651, -------------- SYN_REPORT ------------
Event: time 1584643472.222587, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00e9
Event: time 1584643472.222587, type 1 (EV_KEY), code 115 (KEY_VOLUMEUP), value 0
Event: time 1584643472.222587, -------------- SYN_REPORT ------------
Event: time 1584643474.054616, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00ea
Event: time 1584643474.054616, type 1 (EV_KEY), code 114 (KEY_VOLUMEDOWN), value 1
Event: time 1584643474.054616, -------------- SYN_REPORT ------------
Event: time 1584643474.206614, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00ea
Event: time 1584643474.206614, type 1 (EV_KEY), code 114 (KEY_VOLUMEDOWN), value 0
Event: time 1584643474.206614, -------------- SYN_REPORT ------------
Event: time 1584643475.366599, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00b5
Event: time 1584643475.366599, type 1 (EV_KEY), code 163 (KEY_NEXTSONG), value 1
Event: time 1584643475.366599, -------------- SYN_REPORT ------------
Event: time 1584643475.550566, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00b5
Event: time 1584643475.550566, type 1 (EV_KEY), code 163 (KEY_NEXTSONG), value 0
Event: time 1584643475.550566, -------------- SYN_REPORT ------------
Event: time 1584643476.326518, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00b6
Event: time 1584643476.326518, type 1 (EV_KEY), code 165 (KEY_PREVIOUSSONG), value 1
Event: time 1584643476.326518, -------------- SYN_REPORT ------------
Event: time 1584643476.494508, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00b6
Event: time 1584643476.494508, type 1 (EV_KEY), code 165 (KEY_PREVIOUSSONG), value 0
Event: time 1584643476.494508, -------------- SYN_REPORT ------------
Event: time 1584643477.014567, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00cd
Event: time 1584643477.014567, type 1 (EV_KEY), code 164 (KEY_PLAYPAUSE), value 1
`
and `killall gsd-media-keys` doesn't work at all

**Comment by gittyup444** [comment]
I'm also experiencing this issue on a relatively fresh install of 5.1.2 Hera - Win+T fails as well as shortcuts i setup myself like Win+E for home and Win+I for internet browser also stop working. I've just disabled the only chrome app that I've recently added (Google Duo) to see if that helps, otherwise I'm at a loss to what might be causing this.

**Comment by sbarrow** [comment]
This has been happening intermittently but very often for me. Attaching some logs. It was working for most of the day, but I logged in around 3:17pm (15:17) and now none of my keyboard shortcuts work. Typically, killing gsd-media-keys or resetting individual shortcut keys in system settings fixes it.

[lightdm.log](https://github.com/elementary/gala/files/4640871/lightdm.log)
[seat0-greeter.log](https://github.com/elementary/gala/files/4640872/seat0-greeter.log)
[syslog.txt](https://github.com/elementary/gala/files/4640873/syslog.txt)
[x-0.log](https://github.com/elementary/gala/files/4640874/x-0.log)
[x-1.log](https://github.com/elementary/gala/files/4640875/x-1.log)

**Comment by davidmhewitt** [comment]
Looks like there are some useful troubleshooting steps here:
https://askubuntu.com/a/1220446

Apparently this can be related to Google Chrome's handling of media keys. So if you use Chrome, definitely worth checking.

**Comment by sbarrow** [comment]
I've followed these steps but no error is ever produced in the logs so I'm not sure where to go from here, except completely disable Chrome media keys which is far from ideal.

**Comment by davidmhewitt** [comment]
@sbarrow Agree that disabling Chrome media keys isn't a long-term solution, but since you say this is happening often, I'd be interested to know if disabling them stops or reduces the problem. Then we can start to narrow down on a reproducible test case hopefully.

I've had a trawl through the logs and there's nothing obvious in there as you say.

**Comment by vkaam** [comment]
In my experience, disabling Chrome media keys completely stopped the problem from occurring. I have not experienced the problem again since my comment in February.

**Comment by dcervenkov** [comment]
If you are talking about the `#hardware-media-key-handling` flag, I've had that one disabled for months and still get the problem occasionally. `killall gsd-media-keys` fixes it.

**Comment by davidmhewitt** [comment]
@dcervenkov Can you confirm if you use any other apps that would handle media keys (e.g. Spotify or similar)?

**Comment by dcervenkov** [comment]
@davidmhewitt Yes, I indeed use Spotify.

**Comment by sbarrow** [comment]
@davidmhewitt I disabled chrome media keys. Since this is intermittent I'll want to run for a couple of days before making a call on whether or not it worked.

**Comment by sbarrow** [comment]
Issue hasn't come up since then, hopefully whatever it is will be fixed with a Chrome update.

**Comment by davidmhewitt** [comment]
Yeah, it's hard to know whether this is a Chrome issue or an issue with gsd-media-keys without doing some really in-depth analysis. I believe the Spotify desktop app is built on top of Chromium technologies too, so it's expected that it would cause the same issues.

It's also possible the issue has been fixed in a newer version of gsd-media-keys, and elementary will get a newer version in the next major release (elementary OS 6.0). I'm usually a firefox user, but I can try and force myself to use Chrome for a few days on our internal 6.0 builds and see if I come across the issue.

**Comment by maciej-kaznowski** [comment]
Firefox user here with this issue, although I do have chrome and chromium installed (but they're not auto starting). 

`killall gsd-media-keys` works for the time being.

**Comment by sbarrow** [comment]
I'm still having this issue even with the chrome setting being done. Less so than before and now it seems to stop some shortcuts and not others. Right now my multitasking view and workspace switching shortcuts are working, my volume controls, lock screen shortcut, terminal, and a couple others are not working. Killing gsd-media-keys does seem to fix it though.

**Comment by vikasnataraja** [comment]
So it looks like this is at least partly a Chrome issue. For me, `killall gsd-media-keys` works about half the time. Sometimes it only restores volume button functionality and sometimes it doesn't even do that. @davidmhewitt 's suggestion about Chrome causing the problem seems to be be correct because I disabled Chrome's media keys here: `chrome://flags/#hardware-media-key-handling` and then relaunched Chrome which then restored functionality for all media keys.

**Comment by camilova** [comment]
Hi, i'm facing an issue that `hot corners` stop working some times randomly, and it occurs like with this issue too, normally shortcuts stop working and then hot corners too. I see that hot corners are setted on adjust but they dont respond.

For me, `hot corners` and `shortcuts` work after restart or `sudo service lightdm restart`

Could both issues be related or hot corners are failing due another thing? (I dont know if both are controlled by same process)

**Comment by Akryum** [comment]
I just had this issue with the media keys that stopped working after waking up the computer from sleep. `killall gsd-media-keys` solved it.

**Comment by camilova** [comment]
I confirm what @Akryum says, It solves the issue and media keys works again. Is there a way to run this just after wake up? to automate it as monkey patch.

**Comment by inercia** [comment]
I can also confirm that killing `gsd-media-keys` (altough a new process is started immediately) solves the problem.

**Comment by Akryum** [comment]
I'm still having this issue on waking up eOS 6.1. Have to run `killall gsd-media-keys` to have the keyboard media key to work again.

**Comment by Akryum** [comment]
@tintou Could this issue be re-opened?

**Comment by pckotzer** [comment]
Still broke
