### ISSUE TITLE
Update broke secondary display workspace

### ISSUE THREAD

**Issue by teamcons** [elementary/gala#2387]
### What Happened?

this one appeared at the same time as https://github.com/elementary/gala/issues/2322 in a recent update
Making Gala effectively a one-workspace, one-monitor window manager

going in multitasking, the window on the secondary screen is just a grey empty space.
this happens only in multitasking.
The window on that secondary screen does not show anywhere there

![Image](https://github.com/user-attachments/assets/6b39d374-ee62-4980-9e8a-d3a3bfa990cf)

### Steps to Reproduce

have a secondary screen
have possibly this:  https://github.com/elementary/gala/issues/2322 (so up to date system i guess)

try using multitasking

### Expected Behavior

workspace in multitasking on secondary screen

### OS Version

8.x (Circe)

### Session Type

Secure Session (Wayland)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
nothing new seems to show in dmesg when trying this

> sudo tail -f /var/log/syslog



2025-05-15T13:54:35.824079+02:00 Thonkpod io.elementary.d[1722]: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed
2025-05-15T13:54:35.827240+02:00 Thonkpod io.elementary.d[1722]: message repeated 5 times: [ gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed]
2025-05-15T13:54:36.234315+02:00 Thonkpod gala[1631]: meta_workspace_index: assertion 'META_IS_WORKSPACE (workspace)' failed
2025-05-15T13:54:36.237391+02:00 Thonkpod io.elementary.d[1722]: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed
2025-05-15T13:54:36.237600+02:00 Thonkpod io.elementary.d[1722]: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed
2025-05-15T13:54:40.530997+02:00 Thonkpod gala[1631]: meta_workspace_index: assertion 'META_IS_WORKSPACE (workspace)' failed
2025-05-15T13:54:40.531747+02:00 Thonkpod gala[1631]: meta_workspace_index: assertion 'META_IS_WORKSPACE (workspace)' failed
2025-05-15T13:54:40.537093+02:00 Thonkpod io.elementary.d[1722]: gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed
2025-05-15T13:54:40.538842+02:00 Thonkpod io.elementary.d[1722]: message repeated 3 times: [ gtk_box_remove: assertion 'gtk_widget_get_parent (child) == (GtkWidget *)box' failed]
2025-05-15T13:55:35.524346+02:00 Thonkpod pcloud.desktop[1978]: Current AppImage hash is:  5c057e6ac58c9d03f4033145e66f50dd193100b4e2bf8acb6bee8e2c26c5dd68
```

**Comment by PavloMuravyov** [comment]
In my case, when I try to use the Multitasking View, the system "kills" Wingpanel. None of the indicators work, and in the app menu only the search function is operational. The mouse cannot focus on any app, and it is not possible to launch any applications. Only restarting Wingpanel makes it usable again.

This issue started after the latest system update some hours ago.

**Comment by lenemter** [comment]
@PavloMuravyov Fixed in https://github.com/elementary/gala/pull/2391, new package will be built soon

**Comment by leonardo-lemos** [comment]
@lenemter Can we close this issue?

**Comment by lenemter** [comment]
@teamcons I haven't touched any multimonitor code. Did the new release fix the issue?

**Comment by cyrneko** [comment]
> [@teamcons](https://github.com/teamcons) I haven't touched any multimonitor code. Did the new release fix the issue?

`gala --version` gives me `Gala 8.2.1`, and I can still reproduce this. I updated maybe say, 4 hours ago?

**Comment by leonardo-lemos** [comment]
> > [@teamcons](https://github.com/teamcons) I haven't touched any multimonitor code. Did the new release fix the issue?
> 
> `gala --version` gives me `Gala 8.2.1`, and I can still reproduce this. I updated maybe say, 4 hours ago?
> 
> (well, unless y'all are testing in dailies, in which case 🥴)

The fix will be in the next release (8.2.2)

**Comment by cyrneko** [comment]
> > > [@teamcons](https://github.com/teamcons) I haven't touched any multimonitor code. Did the new release fix the issue?
> > 
> > 
> > `gala --version` gives me `Gala 8.2.1`, and I can still reproduce this. I updated maybe say, 4 hours ago?
> > (well, unless y'all are testing in dailies, in which case 🥴)
> 
> The fix will be released in the next version (8.2.2)

gotcha! error on my part then, thank you all! <3
