### ISSUE TITLE
Multitasking view occasionally glitching out

### ISSUE THREAD

**Issue by jmvrbanac** [elementary/gala#458]
I'm not sure exactly how to consistently reproduce this, but I'm a heavy multitasking view user and I've noticed that usually several times a day I'll get a glitchy view where only a few of the open windows show up and you see one of the windows full sized behind them all like such:

![multitaskview_issue](https://user-images.githubusercontent.com/1307592/52226773-7de4af80-2873-11e9-91db-ee3893918cfb.JPG)

Once I get out of it and open up the view again, it goes back to normal. So it's not detrimental, it's just quite annoying when it happens.

I'm still trying to figure out how to consistently reproduce the issue and I'm not sure if this is related to #305, but it seemed different enough to get a new issue rolling. 

Elementary version: 5.0 Juno
GTK: 3.22.30
Kernel: 4.15.0-43-generic
Nvidia Driver: 390.77

**Comment by peteruithoven** [comment]
I've fixed #305, which was tiling specific, I agree this should be something else. To rule it out you could try the pull request. 

There is a change this is a graphics driver issue. 
How did you select the nvidia driver version? 
Could you try using `sudo ubuntu-drivers autoinstall`
Could you try installing the following ppa to get more recent drivers? 
https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa

**Comment by jmvrbanac** [comment]
Re: How did I select the driver version:
Through the AppCenter, under the drivers section.

I'll give changing the drivers out a try after my workday is over.

**Comment by peteruithoven** [comment]
>  Through the AppCenter, under the drivers section.

But this always shows multiple versions? Or is that just me?

**Comment by jmvrbanac** [comment]
Oh... :grimacing:  _:: trying to remember when I installed this system a couple weeks ago ::_ I think it might have showed up as an option when I was first updating the system after install. All I remember is that I didn't do anything special and it was uneventful (a very good thing lol).

**Comment by jmvrbanac** [comment]
I tried with the Nvidia PPA `410.78` drivers and the issue is still there. I'll give `415.27` a shot and report back.

**Comment by lenemter** [comment]
Closing as stale
