### ISSUE TITLE
Moving a left virtual desktop does not work.

### ISSUE THREAD

**Issue by kmalkenneth** [elementary/gala#696]
Pressing the super + alt + left key combination does not move the window to the left virtual desktop.

**Comment by Blast-City** [comment]
> Pressing the super + alt + left key combination does not move the window to the left virtual desktop.

Hi.

Which workspace do you have the window? First?

**Comment by kmal-kenneth** [comment]
> > Pressing the super + alt + left key combination does not move the window to the left virtual desktop.
> 
> Hi.
> 
> Which workspace do you have the window? The first one?

You can move the window to the right virtual desktop, but do not return it to the left using a keyboard.

**Comment by Blast-City** [comment]
Hi.
I'm not sure if I'm understanding you. Sorry.
Is it the same issue as #187 or you can't move the window to the left workspace if the window is on the second workspace?
Try this:
1- Open an app.
2- Switch to right workspace (Super+Right)
3- Open an app
4- Try to move the app to the left workspace with Super+Alt+Left.
The above should be working. If not check you keyboard shortcuts on system settings.

**Comment by kmal-kenneth** [comment]
I can't move the window to the left workspace if the window is on the second workspace or other workspace.

I discovered that if I release the superkey first it works.

This behavior is very strange.

**Comment by Blast-City** [comment]
> I can't move the window to the left workspace if the window is on the second workspace or other workspace.
> 
> I discovered that if I release the superkey first it works.
> 
> This behavior is very strange.
> 
> Sorry, my english is very bad.

I can't replicate your issue. On my computer as soon as I press the left key the window is moved to the left workspace. Maybe you could try to reset elementary settings or add a new user and test if the same happens on a new profile.

P.S: Your English is fine.

**Comment by kmal-kenneth** [comment]
Yesterday I installed Elementary OS again. The problem persists. I still have no idea how to correct it.

**Comment by ryonakano** [comment]
I followed @Blast-City's scenario and can move a window to the left workspace.

**Comment by kmal-kenneth** [comment]
A few days ago I tried the pantheon on opensuse and had the same problem ... I think it's on my PC.

**Comment by lenemter** [comment]
Closing as stale. If you still can reproduce the issue in OS 8, please reply here and I'll reopen it
